// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDx9E-lTPpD6UZRw_Kxp6j9J4KxUVm0v_U',
    appId: '1:1046212845648:web:0bebf62d869e09d761f155',
    messagingSenderId: '1046212845648',
    projectId: 'beadaisy-5f044',
    authDomain: 'beadaisy-5f044.firebaseapp.com',
    storageBucket: 'beadaisy-5f044.firebasestorage.app',
    measurementId: 'G-ZCBQPRLMVX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCE4rCn3-yiDyU58k-wPydT9uFaaGa-zHI',
    appId: '1:1046212845648:android:29845c293c692cc861f155',
    messagingSenderId: '1046212845648',
    projectId: 'beadaisy-5f044',
    storageBucket: 'beadaisy-5f044.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDha4BMJJc0yVQ6NQhHOTqPV_37EO4p89k',
    appId: '1:1046212845648:ios:a12da7248b5829f361f155',
    messagingSenderId: '1046212845648',
    projectId: 'beadaisy-5f044',
    storageBucket: 'beadaisy-5f044.firebasestorage.app',
    iosBundleId: 'com.example.appbaru',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDha4BMJJc0yVQ6NQhHOTqPV_37EO4p89k',
    appId: '1:1046212845648:ios:a12da7248b5829f361f155',
    messagingSenderId: '1046212845648',
    projectId: 'beadaisy-5f044',
    storageBucket: 'beadaisy-5f044.firebasestorage.app',
    iosBundleId: 'com.example.appbaru',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDx9E-lTPpD6UZRw_Kxp6j9J4KxUVm0v_U',
    appId: '1:1046212845648:web:6703301db9eb005b61f155',
    messagingSenderId: '1046212845648',
    projectId: 'beadaisy-5f044',
    authDomain: 'beadaisy-5f044.firebaseapp.com',
    storageBucket: 'beadaisy-5f044.firebasestorage.app',
    measurementId: 'G-EKLM2B2DG7',
  );

}